### PR TITLE
fix: dbconnection route types are broken

### PR DESCRIPTION
**Pull request by danielgent**
I've not fixed it, I'm assuming we should delete this route as it seems duplicated elsewhere *and* it's been broken since who knows when!

### CODE REVIEW

**Review by markusahlstrand — APPROVED** [review]
Think this change looks right.. Probably need to add a test here..

**Comment by danielgent** [comment]
> Think this change looks right.. Probably need to add a test here..

@markusahlstrand there are still lots of errors.  we're not checking the types *at all* here

Unless we run a test, it looks like TypeScript isn't check.  `node tsoa.mjs` doesn't do the same as running `tsc`

**Comment by danielgent** [comment]
ah I've just seen your comment here Markus saying
https://github.com/sesamyab/auth/pull/133#discussion_r1322069490 `It's the password route so I would prefer fixing it :)`

I'll pick this PR up again now

**Comment by danielgent** [comment]
I'm pretty sure I fixed this elsewhere now I got typescript running everywhere :muscle:

**Pull request closed without merging**
