### PR TITLE
chore: upload any pngs from diffs

### PR DESCRIPTION
**Pull request by markusahlstrand**
Not tested but it looks like this should work

### CODE REVIEW

**Comment by danielgent** [comment]
How does it work? Where are the artefacts?

**Comment by danielgent** [comment]
image

**Comment by markusahlstrand** [comment]
Think they will be uploaded if they exist, but hard to know before it happens :)

**Comment by danielgent** [comment]
> Think they will be uploaded if they exist, but hard to know before it happens :)

Best way is to cause an error. It's quite easy, just randomly delete or make changes to the JSX :wink: 

I'll try it now

**Comment by danielgent** [comment]
Nope. Tests fail but nothing happens. I don't think this is the most important thing for me to look into (thus why it's not done)

I think your time Markus would be better spent playing around with Docker and getting something working. Maybe give the other devs a shout they're all on Macs and they seem to be updating snapshots

I don't mind how everyone does it, as long as people do it :+1:

**Comment by markusahlstrand** [comment]
Think it's skipped because the tests fail. I'll see if there's an easy fix. For me I loose an hour every time this happens so it's a good investment.

**Comment by markusahlstrand** [comment]
> Nope. Tests fail but nothing happens. I don't think this is the most important thing for me to look into (thus why it's not done)
> 
> I think your time Markus would be better spent playing around with Docker and getting something working. Maybe give the other devs a shout they're all on Macs and they seem to be updating snapshots
> 
> I don't mind how everyone does it, as long as people do it 👍

All the devs are just quietly suffering instead of fixing the issue :)

**Comment by markusahlstrand** [comment]
Took 60 seconds of gooling to fix. Well invested time.

**Comment by markusahlstrand** [comment]
Would be nice to upload the test report.. Do you know where that is stored?

**Comment by danielgent** [comment]
> > Nope. Tests fail but nothing happens. I don't think this is the most important thing for me to look into (thus why it's not done)
> > I think your time Markus would be better spent playing around with Docker and getting something working. Maybe give the other devs a shout they're all on Macs and they seem to be updating snapshots
> > I don't mind how everyone does it, as long as people do it 👍
> 
> All the devs are just quietly suffering instead of fixing the issue :)

image

**Comment by danielgent** [comment]
image

Looks like it's there

**Comment by danielgent** [comment]
> Took 60 seconds of gooling to fix. Well invested time.

I've been burned by spending days on CI/CD testing improvements :joy:

**Comment by danielgent** [comment]
image

Great stuff @markusahlstrand. You can be the testing guy now :saluting_face: 

I wonder if we should put this on a Sesamy blog article. I always seem to end up on the cutting edge of testing. My last boss made this package following our usage or react testing library https://www.npmjs.com/package/eslint-plugin-testing-library

I think you can beat 5 million weekly downloads :tonga:

**Pull request merged**
