### PR TITLE
fix: application adapter

### PR DESCRIPTION
**Pull request by markusahlstrand**
I abandoned this before as I didn't need it and left it in a not so great state. This should fix it even though it's not 100% complete yet.

### CODE REVIEW

**Comment by danielgent** [comment]
@markusahlstrand :x:

**Comment by danielgent** [comment]
@markusahlstrand I fixed the types so the unit tests pass *BUT* the integration tests go :boom:

**Comment by danielgent** [comment]
A lot of them are giving ` TypeError: Body is unusable`

**Comment by markusahlstrand** [comment]
Did something stupid in test integration test setup and tried to read the same response body twice.

**Pull request merged**
