### PR TITLE
fix: upgrade packages

### PR DESCRIPTION
**Pull request by markusahlstrand**
Always on latest and greatest!

### CODE REVIEW

**Comment by markusahlstrand** [comment]
Interesting... looks like the fetch has changes? Works locally which is odd. Maybe it's the jsdom-test adapter?

**Comment by danielgent** [comment]
> Interesting... looks like the fetch has changes? Works locally which is odd. Maybe it's the jsdom-test adapter?

This is why I prefer something like renovate bot upgrading different packages on different PRs *all the time*  :smile: 

At least in this case it has failed on the CI/CD.  The most fun is when in a week we get an odd production issue and then we have no idea :smile:

**Comment by danielgent** [comment]
https://github.com/sesamyab/auth/pull/251 :see_no_evil:   We can reopen this and have the bot do its work :smile: 

As this project is public we can also set up proper renovate actions (paid feature on private repos)

**Comment by danielgent** [comment]
It can do things like not upgrade to the latest NPM version until X days have passed -> https://docs.renovatebot.com/configuration-options/#minimumreleaseage

Which would stop us accidentally getting bleeding edge packages that might then have new updates pushed straight away due to bugs (easily done)

**Comment by danielgent** [comment]
I'm taking the thumbs up as a _yes please enable renovate bot_ :smile:

**Comment by danielgent** [comment]
Closing as I've enabled el bot de renovacion

**Pull request closed without merging**
