### PR TITLE
fix: refactor rename-id

### PR DESCRIPTION
**Pull request by markusahlstrand**
Changed to enrichUser now is renameId instead. This way we should be able to use the same function for all auth0 endpoints.

### CODE REVIEW

**Comment by markusahlstrand** [comment]
It seems that we are doing this differently for other entities.. In those cases we handle the mapping of the id field straight in the adapter.. Not sure what's best?

**Comment by danielgent** [comment]
> It seems that we are doing this differently for other entities.. In those cases we handle the mapping of the id field straight in the adapter.. Not sure what's best?

Is there even a best? Consistent would be the main thing. We could flip a coin to decide and then reflect in the future on what the best approach was :smile: 

Maybe the tables should just have `user_id`, `log_id`, etc as the PK and there should never have been mappings

**Comment by markusahlstrand** [comment]
Yeah, I have been thinking about if we really should have updated the tables but guess that will be pretty complicated now that there's data in the system...

**Comment by markusahlstrand** [comment]
From the perspective that we consider to change the database it would seem that the correct choice would be to handle it in the adapter? That way it's at least contained and new adapters could handle it correctly

**Comment by danielgent** [comment]
> From the perspective that we consider to change the database it would seem that the correct choice would be to handle it in the adapter? That way it's at least contained and new adapters could handle it correctly

I would agree with this. This PR is a step in the right direction though :+1:

**Pull request merged**
